### ISSUE TITLE
Ошибка в EsiaAuthenticationHandler.CreateTicketAsync, если не указывать scope "fullname"

### ISSUE THREAD

**Issue by miegir** [xeltan/EsiaNET#8]
Если не указывать "fullname" в scope (мы используем только "snils"), то возникает следующая ошибка в методе https://github.com/xeltan/EsiaNET/blob/09cbcb4f8cc86db7976226172f10eeefc8713116/EsiaNET.AspNetCore.Authentication/EsiaAuthenticationHandler.cs#L139
```
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at System.Security.Claims.Claim..ctor(String type, String value, String valueType, String issuer, String originalIssuer, ClaimsIdentity subject, String propertyKey, String propertyValue)
   at System.Security.Claims.Claim..ctor(String type, String value, String valueType, String issuer)
   at EsiaNET.AspNetCore.Authentication.EsiaAuthenticationHandler.CreateTicketAsync(ClaimsIdentity identity, AuthenticationProperties properties, OAuthTokenResponse tokens)
   at EsiaNET.AspNetCore.Authentication.EsiaAuthenticationHandler.HandleRemoteAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()

**Comment by miegir** [comment]
Как показывает отладка, возвращается не-null personInfo, но Name в нем по понятным причинам не заполнен:
![image](https://user-images.githubusercontent.com/7460974/131301509-4eae4a68-62f2-457e-821b-8e6fee320c6c.png)
Из-за этого, очевидно, падает в этой строке
https://github.com/xeltan/EsiaNET/blob/09cbcb4f8cc86db7976226172f10eeefc8713116/EsiaNET.AspNetCore.Authentication/EsiaAuthenticationHandler.cs#L158

**Comment by xeltan** [comment]
исправлено в версии 6.0.0
